### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by builderjer** [NeonGeckoCom/neon-tts-plugin-larynx_server#11]
I've been working on trying to get this to work with the latest ovos-core and such.  The first issue was `neon-utils` was clashing at some point.  The only thing that was used from it was a parser to use ssml.  I eliminated that and things started loading.  After changing a few other things, I came across an error that I don't know where to go to next.

```
2022-02-25 03:38:32.511 - OVOS - mycroft.audio.speech:mute_and_speak:99 - ERROR - TTS execution failed.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mycroft/audio/speech.py", line 94, in mute_and_speak
    tts.execute(utterance, ident, listen)
  File "/home/mycroft/.local/lib/python3.8/site-packages/ovos_plugin_manager/templates/tts.py", line 552, in execute
    self._execute(sentence, ident, listen, **kwargs)
  File "/home/mycroft/.local/lib/python3.8/site-packages/ovos_plugin_manager/templates/tts.py", line 575, in _execute
    if sentence_hash in self.cache:  # load from cache
  File "/home/mycroft/.local/lib/python3.8/site-packages/ovos_plugin_manager/templates/tts.py", line 372, in cache
    return self.caches[self.tts_id]
KeyError: 'LarynxServerTTSPlugin/northern_english_male-glow_tts/en-us'
```
`self.caches = {'LarynxServerTTSPlugin/northern_english_male/en-us': <ovos_plugin_manager.utils.tts_cache.TextToSpeechCache object at 0x7f6e5f1040>}`

so I think the key is there, so I don't know where to go next.  Maybe in [OPM](https://github.com/OpenVoiceOS/OVOS-plugin-manager)

[this commit](https://github.com/builderjer/neon-tts-plugin-larynx_server/commit/f5e2083ed0e1b87110c710aaa1bb04cb3804121d) are the changes I made.

**Comment by NeonDaniel** [comment]
Sorry this issue got buried in my notifications.. I think things should be resolved now with the latest release (#15), `neon-utils` dependency has been dropped and OPM updated. Please re-open if the issue persists
